In [1]:
from car_list_func import get_brand_list, get_model_list, get_year_list, get_detail_list, get_option_list

In [2]:
import requests

In [3]:
client_id = "1c88a2fa-5208-45df-8930-63530b454779"
client_secret = "c2fb5ce6-2196-4bff-8540-b34509dae730"
access_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX3R5cGUiOiIxIiwic2NvcGUiOlsicmVhZCJdLCJzZXJ2aWNlX25vIjoiMDAwMDA0OTU3MDAyIiwiZXhwIjoxNzM0OTI0OTkwLCJhdXRob3JpdGllcyI6WyJJTlNVUkFOQ0UiLCJQVUJMSUMiLCJCQU5LIiwiRVRDIiwiU1RPQ0siLCJDQVJEIl0sImp0aSI6IjA3YzNiMDYzLWE0OGItNDhmNi1iYzRiLTc5NWEwMTAxM2NhZCIsImNsaWVudF9pZCI6IjFjODhhMmZhLTUyMDgtNDVkZi04OTMwLTYzNTMwYjQ1NDc3OSJ9.KabIhIZWpkFRxy5BzJ_NGJsp6PQFuh2K3mF576clR4ypIREJ_k4RlR-hrv09_jq9iznW84iRZ4hDFc3W2EZxAYLeVFFGthqowuV5sA-30lAP6kVNF8IMOPXxJIJFD9eJIL-xoZe5dzg-UuofXZqrW6cYpjUgCgOA59ynjffuXcPmajamuIJjKc5Czhm-KXzjhumuyVsdsidbUUEFZkZOY7RjaQS_u5jtc8WB0RWJzfC_u-h2_nBQaLW2Pyme71vD0940UZjPhkuiLTmM4bxCuxaH0sX8xM1P2S1jXQQnbS2yh5YVQEXCLBV0jnRKrUBANGOr7HHkTU-HFVExl5hz8w"

In [4]:
headers = {
    "Authorization": access_token,  # 발급받은 토큰으로 대체
    "Content-Type": "application/json"
}

In [23]:
import pprint
import json

In [25]:
brand_list = get_brand_list(headers)

디코딩 된 응답: {"result":{"code":"CF-00000","extraMessage":"","message":"성공"},"data":[{"cd":"AD","nm":"AD"},{"cd":"CT&T","nm":"CT&T"},{"cd":"기아","nm":"기아"},{"cd":"기타","nm":"기타"},{"cd":"대우","nm":"대우"},{"cd":"대창","nm":"대창"},{"cd":"삼성","nm":"삼성"},{"cd":"쌍용","nm":"쌍용"},{"cd":"외산","nm":"외산"},{"cd":"현EV","nm":"현EV"},{"cd":"현대","nm":"현대"}]}
{
    "result": {
        "code": "CF-00000",
        "extraMessage": "",
        "message": "성공"
    },
    "data": [
        {
            "cd": "AD",
            "nm": "AD"
        },
        {
            "cd": "CT&T",
            "nm": "CT&T"
        },
        {
            "cd": "기아",
            "nm": "기아"
        },
        {
            "cd": "기타",
            "nm": "기타"
        },
        {
            "cd": "대우",
            "nm": "대우"
        },
        {
            "cd": "대창",
            "nm": "대창"
        },
        {
            "cd": "삼성",
            "nm": "삼성"
        },
        {
            "cd": "쌍용",
            "nm": "쌍용"
        },
        {
            "cd": "외산",
            "nm": "외산"
        },
        {
            "cd": "현EV",
            "nm": "현EV"
        },
        {
            "cd": "현대",
            "nm": "현대"
        }
    ]
}

In [29]:
print(json.dumps(brand_list, indent=4, ensure_ascii=False))

{
    "result": {
        "code": "CF-00000",
        "extraMessage": "",
        "message": "성공"
    },
    "data": [
        {
            "cd": "AD",
            "nm": "AD"
        },
        {
            "cd": "CT&T",
            "nm": "CT&T"
        },
        {
            "cd": "기아",
            "nm": "기아"
        },
        {
            "cd": "기타",
            "nm": "기타"
        },
        {
            "cd": "대우",
            "nm": "대우"
        },
        {
            "cd": "대창",
            "nm": "대창"
        },
        {
            "cd": "삼성",
            "nm": "삼성"
        },
        {
            "cd": "쌍용",
            "nm": "쌍용"
        },
        {
            "cd": "외산",
            "nm": "외산"
        },
        {
            "cd": "현EV",
            "nm": "현EV"
        },
        {
            "cd": "현대",
            "nm": "현대"
        }
    ]
}

In [32]:
import pandas as pd

In [33]:
df = pd.DataFrame(brand_list["data"])
df

      cd    nm
0     AD    AD
1   CT&T  CT&T
2     기아    기아
3     기타    기타
4     대우    대우
5     대창    대창
6     삼성    삼성
7     쌍용    쌍용
8     외산    외산
9    현EV   현EV
10    현대    현대

In [35]:
# 파일 경로 설정 (저장할 파일명)
file_path = "data/brand_list.json"

# JSON 데이터를 파일에 저장
with open(file_path, "w", encoding="utf-8") as file:
    json.dump(brand_list, file, indent=4, ensure_ascii=False)  # 보기 좋게 저장
    print(f"JSON 데이터가 {file_path}에 저장되었습니다.")

JSON 데이터가 data/brand_list.json에 저장되었습니다.

In [39]:
model_list = get_model_list(headers, brand_code)

디코딩 된 응답: {"result":{"code":"CF-00000","extraMessage":"","message":"성공"},"data":[{"cd":"i30","nm":"i30"},{"cd":"i40","nm":"i40"},{"cd":"그랜져","nm":"그랜져"},{"cd":"넥쏘","nm":"넥쏘"},{"cd":"다이너스티","nm":"다이너스티"},{"cd":"라비타","nm":"라비타"},{"cd":"마이브","nm":"마이브"},{"cd":"맥스크루즈","nm":"맥스크루즈"},{"cd":"베뉴","nm":"베뉴"},{"cd":"베라크루즈","nm":"베라크루즈"},{"cd":"베르나","nm":"베르나"},{"cd":"벨로스터","nm":"벨로스터"},{"cd":"스타렉스","nm":"스타렉스"},{"cd":"스타리아","nm":"스타리아"},{"cd":"싼타페","nm":"싼타페"},{"cd":"쏘나타","nm":"쏘나타"},{"cd":"쏠라티","nm":"쏠라티"},{"cd":"아반떼","nm":"아반떼"},{"cd":"아슬란","nm":"아슬란"},{"cd":"아이오닉","nm":"아이오닉"},{"cd":"에쿠스","nm":"에쿠스"},{"cd":"엑센트","nm":"엑센트"},{"cd":"제네시스","nm":"제네시스"},{"cd":"제네시스쿠페","nm":"제네시스쿠페"},{"cd":"캐스퍼","nm":"캐스퍼"},{"cd":"코나","nm":"코나"},{"cd":"클릭","nm":"클릭"},{"cd":"테라칸","nm":"테라칸"},{"cd":"투스카니","nm":"투스카니"},{"cd":"투싼","nm":"투싼"},{"cd":"트라제","nm":"트라제"},{"cd":"팰리세이드","nm":"팰리세이드"},{"cd":"포터(캠핑카)","nm":"포터(캠핑카)"}]}

In [61]:
print(json.dumps(model_list, indent=4, ensure_ascii=False))

TypeError: 'str' object is not callable

In [41]:
df = pd.DataFrame(model_list["data"])
df

         cd       nm
0       i30      i30
1       i40      i40
2       그랜져      그랜져
3        넥쏘       넥쏘
4     다이너스티    다이너스티
5       라비타      라비타
6       마이브      마이브
7     맥스크루즈    맥스크루즈
8        베뉴       베뉴
9     베라크루즈    베라크루즈
10      베르나      베르나
11     벨로스터     벨로스터
12     스타렉스     스타렉스
13     스타리아     스타리아
14      싼타페      싼타페
15      쏘나타      쏘나타
16      쏠라티      쏠라티
17      아반떼      아반떼
18      아슬란      아슬란
19     아이오닉     아이오닉
20      에쿠스      에쿠스
21      엑센트      엑센트
22     제네시스     제네시스
23   제네시스쿠페   제네시스쿠페
24      캐스퍼      캐스퍼
25       코나       코나
26       클릭       클릭
27      테라칸      테라칸
28     투스카니     투스카니
29       투싼       투싼
30      트라제      트라제
31    팰리세이드    팰리세이드
32  포터(캠핑카)  포터(캠핑카)

In [3]:
import datetime

# 오늘로부터 3일 뒤 날짜 계산
today = datetime.date.today()
three_days_later = today + datetime.timedelta(days=3)
start_date = three_days_later.strftime("%Y%m%d")

In [74]:
year_list = get_year_list(headers, brand_code, model_code, start_date)

디코딩 된 응답: {"result":{"code":"CF-00000","extraMessage":"","message":"성공"},"data":[{"cd":"2024A","nm":"2024년+06월+19일+이후+등록차량"},{"cd":"2024B","nm":"2024년+06월+18일+이전+등록차량"},{"cd":"2023","nm":"2023"},{"cd":"2022","nm":"2022"},{"cd":"2021","nm":"2021"},{"cd":"2020","nm":"2020"},{"cd":"2019","nm":"2019"},{"cd":"2018","nm":"2018"},{"cd":"2017","nm":"2017"},{"cd":"2016","nm":"2016"},{"cd":"2015","nm":"2015"},{"cd":"2014","nm":"2014"},{"cd":"2013","nm":"2013"},{"cd":"2012","nm":"2012"},{"cd":"2011","nm":"2011"},{"cd":"2010","nm":"2010"},{"cd":"2009","nm":"2009"},{"cd":"2008","nm":"2008"}]}

In [76]:
year_list["data"][0]["cd"]

'2024A'

In [77]:
# 요청값 목록
headers
brand_code = '현대'
model_code = '제네시스'
start_date = three_days_later.strftime("%Y%m%d")
year_code = year_list["data"][0]["cd"]
detail_code = detail_list["data"][26]["cd"]

In [79]:
detail_list= get_detail_list(headers, brand_code, model_code, year_code)

디코딩 된 응답: {"result":{"code":"CF-00000","extraMessage":"","message":"성공"},"data":[{"cd":"G70+2.0T+Shooting+Brake","nm":"G70+2.0T+Shooting+Brake"},{"cd":"G70+2.5T+Shooting+Brake","nm":"G70+2.5T+Shooting+Brake"},{"cd":"New+제네시스+GV70+가솔린+2.5+터보","nm":"New+제네시스+GV70+가솔린+2.5+터보"},{"cd":"New+제네시스+GV70+가솔린+3.5+터보","nm":"New+제네시스+GV70+가솔린+3.5+터보"},{"cd":"제네시스+G80+2.2d(3세대)","nm":"제네시스+G80+2.2d(3세대)"},{"cd":"제네시스+G80+2.5T(2024년형)","nm":"제네시스+G80+2.5T(2024년형)"},{"cd":"제네시스+G80+2.5T(3세대)","nm":"제네시스+G80+2.5T(3세대)"},{"cd":"제네시스+G80+3.5T(2024년형)","nm":"제네시스+G80+3.5T(2024년형)"},{"cd":"제네시스+G80+3.5T(3세대)","nm":"제네시스+G80+3.5T(3세대)"},{"cd":"제네시스+G80+EV","nm":"제네시스+G80+EV"},{"cd":"제네시스+G90+3.3T","nm":"제네시스+G90+3.3T"},{"cd":"제네시스+G90+3.5T","nm":"제네시스+G90+3.5T"},{"cd":"제네시스+G90+3.5T+일렉트릭+슈퍼차저","nm":"제네시스+G90+3.5T+일렉트릭+슈퍼차저"},{"cd":"제네시스+G90+3.8","nm":"제네시스+G90+3.8"},{"cd":"제네시스+G90+5.0","nm":"제네시스+G90+5.0"},{"cd":"제네시스+GV60","nm":"제네시스+GV60"},{"cd":"제네시스+GV70+EV","nm":"제네시스+GV70+EV"},{"cd":"제네시스+GV70+가솔린+2.5터보","nm":"제네시스+GV70+가솔린+2.5터보"},{"cd":"제네시스+GV70+가솔린+3.5터보","nm":"제네시스+GV70+가솔린+3.5터보"},{"cd":"제네시스+GV70+디젤+2.2","nm":"제네시스+GV70+디젤+2.2"},{"cd":"제네시스+GV80+2.5T","nm":"제네시스+GV80+2.5T"},{"cd":"제네시스+GV80+3.0(디젤)","nm":"제네시스+GV80+3.0(디젤)"},{"cd":"제네시스+GV80+3.5T","nm":"제네시스+GV80+3.5T"},{"cd":"제네시스+New+GV80+2.5T","nm":"제네시스+New+GV80+2.5T"},{"cd":"제네시스+New+GV80+3.5T","nm":"제네시스+New+GV80+3.5T"},{"cd":"제네시스+New+GV80+쿠페+2.5T","nm":"제네시스+New+GV80+쿠페+2.5T"},{"cd":"제네시스+New+GV80+쿠페+3.5-48V","nm":"제네시스+New+GV80+쿠페+3.5-48V"},{"cd":"제네시스+New+GV80+쿠페+3.5T","nm":"제네시스+New+GV80+쿠페+3.5T"},{"cd":"제네시스+The+new+G70+가솔린2.0+터보","nm":"제네시스+The+new+G70+가솔린2.0+터보"},{"cd":"제네시스+The+new+G70+가솔린2.5+터보","nm":"제네시스+The+new+G70+가솔린2.5+터보"},{"cd":"제네시스+The+new+G70+가솔린3.3+터보","nm":"제네시스+The+new+G70+가솔린3.3+터보"}]}

In [80]:
df = pd.DataFrame(detail_list["data"])
df

                            cd                          nm
0      G70+2.0T+Shooting+Brake     G70+2.0T+Shooting+Brake
1      G70+2.5T+Shooting+Brake     G70+2.5T+Shooting+Brake
2     New+제네시스+GV70+가솔린+2.5+터보    New+제네시스+GV70+가솔린+2.5+터보
3     New+제네시스+GV70+가솔린+3.5+터보    New+제네시스+GV70+가솔린+3.5+터보
4           제네시스+G80+2.2d(3세대)          제네시스+G80+2.2d(3세대)
5        제네시스+G80+2.5T(2024년형)       제네시스+G80+2.5T(2024년형)
6           제네시스+G80+2.5T(3세대)          제네시스+G80+2.5T(3세대)
7        제네시스+G80+3.5T(2024년형)       제네시스+G80+3.5T(2024년형)
8           제네시스+G80+3.5T(3세대)          제네시스+G80+3.5T(3세대)
9                  제네시스+G80+EV                 제네시스+G80+EV
10               제네시스+G90+3.3T               제네시스+G90+3.3T
11               제네시스+G90+3.5T               제네시스+G90+3.5T
12     제네시스+G90+3.5T+일렉트릭+슈퍼차저     제네시스+G90+3.5T+일렉트릭+슈퍼차저
13                제네시스+G90+3.8                제네시스+G90+3.8
14                제네시스+G90+5.0                제네시스+G90+5.0
15                   제네시스+GV60                   제네시스+GV60
16                제네시스+GV70+EV                제네시스+GV70+EV
17         제네시스+GV70+가솔린+2.5터보         제네시스+GV70+가솔린+2.5터보
18         제네시스+GV70+가솔린+3.5터보         제네시스+GV70+가솔린+3.5터보
19            제네시스+GV70+디젤+2.2            제네시스+GV70+디젤+2.2
20              제네시스+GV80+2.5T              제네시스+GV80+2.5T
21           제네시스+GV80+3.0(디젤)           제네시스+GV80+3.0(디젤)
22              제네시스+GV80+3.5T              제네시스+GV80+3.5T
23          제네시스+New+GV80+2.5T          제네시스+New+GV80+2.5T
24          제네시스+New+GV80+3.5T          제네시스+New+GV80+3.5T
25       제네시스+New+GV80+쿠페+2.5T       제네시스+New+GV80+쿠페+2.5T
26    제네시스+New+GV80+쿠페+3.5-48V    제네시스+New+GV80+쿠페+3.5-48V
27       제네시스+New+GV80+쿠페+3.5T       제네시스+New+GV80+쿠페+3.5T
28  제네시스+The+new+G70+가솔린2.0+터보  제네시스+The+new+G70+가솔린2.0+터보
29  제네시스+The+new+G70+가솔린2.5+터보  제네시스+The+new+G70+가솔린2.5+터보
30  제네시스+The+new+G70+가솔린3.3+터보  제네시스+The+new+G70+가솔린3.3+터보

In [81]:
# 요청값 목록
headers
brand_code = '현대'
model_code = '제네시스'
start_date = three_days_later.strftime("%Y%m%d")
year_code = year_list["data"][0]["cd"]
detail_code = detail_list["data"][26]["cd"]
option_code = option_list["data"][0]["cd"]

In [2]:
start_date
year_code
detail_code
option_code

NameError: name 'start_date' is not defined

In [83]:
option_list = get_option_list(headers, brand_code, model_code, year_code, detail_code)

디코딩 된 응답: {"result":{"code":"CF-00000","extraMessage":"","message":"성공"},"data":[{"cd":"61WI6","nm":"5인승+AWD,오토,에어컨,P/S,ABS,AIR-D,IM(가솔린)"}]}

In [84]:
option_list

{'result': {'code': 'CF-00000', 'extraMessage': '', 'message': '성공'},
 'data': [{'cd': '61WI6', 'nm': '5인승+AWD,오토,에어컨,P/S,ABS,AIR-D,IM(가솔린)'}]}

In [85]:
# 요청값 목록
headers
brand_code = '현대'
model_code = '제네시스'
start_date = three_days_later.strftime("%Y%m%d")
year_code = year_list["data"][0]["cd"]
detail_code = detail_list["data"][26]["cd"]
option_code = option_list["data"][0]["cd"]

In [89]:
from dotenv import load_dotenv

load_dotenv()

True